# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: en
dictionaryDefinitions:
    - name: cspell-words
      path: './cspell-words.txt'
      addWords: true
dictionaries:
    - cspell-words
